### ISSUE TITLE
Logstash flush interval

### ISSUE THREAD

**Issue by spa-87** [radoondas/apachebeat#23]
Hello, we use apachebeat with logstash output plugin. I noticed data from apachebeat is uploaded to the server with a large delay. After I launched manually I found out there's flush interval has value 277777h46m40s (by default):
2016/04/18 09:13:33.432573 async.go:70: INFO Flush Interval set to: 277777h46m40s

I tried to set flush_interval to 1 manually but it didn't have affect. Flush interval at logs had the same value.
After I set flush_interval to 2, at logs I got: 555555h33m20s
If I set flush_interval to 3, I get: 833333h20m0s 
and so on... 
So looks like flush_interval parameter is a multiplier for some value.

277777h46m40s is equal to 1 000 000 000 seconds

**Comment by radoondas** [comment]
Hi,
thanks for reporting. 
Unfortunately, I have noticed this also during the weekend. 
I will have a look.

Meanwhile, setting in configuration:
bulk_max_size: 1
or some sane number should help too.

**Comment by radoondas** [comment]
@spa-87 this issue is related to bug fixed in beats by elastic/beats#1280
I have updated vendor folder and all should be now up to date and fixed. 
Could you please retest?

**Comment by spa-87** [comment]
@radoondas thank you for the quick fix! I've tested the new version and it works for me.

**Comment by radoondas** [comment]
@spa-87 Thanks again for reporting.
