### ISSUE TITLE
apache.connections.connsTotal

### ISSUE THREAD

**Issue by rygy** [radoondas/apachebeat#24]
Curious if this field is being correctly parsed?  It seems to record values of 0 consistently, whereas mod_status reports active connections (last line of server-status prior to scoreboard output):

`
210 requests currently being processed, 79 idle workers
`

is connections.connsTotal pulled from the mod_status output line shown above?

**Comment by radoondas** [comment]
@rygy Thanks for question. 
This value is parsed from different line than you expect. 
See: https://github.com/radoondas/apachebeat/blob/master/beater/status.go#L185

If your server-status doesn't contain that line, than it will be always 0. If I am not mistaken this comes from Apache 2.4 (but not sure yet if from extended status)

I'm closing it and if you have more question, please reopen.

**Comment by rygy** [comment]
Interesting as I'm using 2.4 with extended status:

Apache Server Status for localhost (via 127.0.0.1)

Server Version: Apache/2.4.7 (Ubuntu)
Server MPM: event
Server Built: Jan 14 2016 17:45:23
Current Time: Thursday, 02-Jun-2016 16:22:41 UTC
Restart Time: Thursday, 02-Jun-2016 16:08:53 UTC
Parent Server Config. Generation: 1
Parent Server MPM Generation: 0
Server uptime: 13 minutes 48 seconds
Server load: 0.10 0.12 0.14
Total accesses: 281 - Total Traffic: 2.3 MB
CPU Usage: u.78 s.57 cu0 cs0 - .163% CPU load
.339 requests/sec - 2855 B/second - 8.2 kB/request
1 requests currently being processed, 49 idle workers
PID Connections Threads Async connections
total   accepting   busy    idle    writing keep-alive  closing
4327    0   yes 1   24  0   0   0
4328    0   yes 0   25  0   0   0
Sum 0       1   49  0   0   0
_____________W____________________________________..............
................................................................
......................

---

Do you have an example mod-status output in the repo?

**Comment by radoondas** [comment]
@rygy Could you please post here output from machine readable output? 
I mean: IP:PORT/server-status?auto

Also you can find an example [here](https://github.com/radoondas/apachebeat/blob/master/status_examples/server_status_extended)

**Comment by rygy** [comment]
Ah perfect - I guess for some reason it wasn't pulling the ?auto bit -
thanks much for you help!  Very much enjoying apachebeat!
