### ISSUE TITLE
can't kill apachebeat process!

### ISSUE THREAD

**Issue by kkpbbb** [radoondas/apachebeat#7]
Hi I have try it in centos 6.x and found can't kill apachebeat unless use kill -9

Is it a bug ?

thanks

sorry for my bad english

**Comment by radoondas** [comment]
Hi,
apachebeat (or other beats) doesn't have any special start or stop script which would handle 'stoping'. Kill command is the way to stop it. 

Implementer of the beat is usually responsible for this task for each environment.

If you have started your apachebeat in terminal and it is running in terminal as process, simple Ctrl+C should stop apachebeat. 
If you sent your apachebeat to background, either call if back (fg) and stop by Ctrl+C, or execute simple 'kill <PID>' command. However, 'klill -9 <PID>' is not necessary under normal circumstances.

On the other hand, I am thinking of creating a script for start and stop of apachebeat but I cannot promise a thing for this task in near future.
Rado

**Comment by kkpbbb** [comment]
Hi,thanks for your replay
I know golang can't been a "daemon " in linux without other tools like go-daemon
I have try another beats and they do easy quit with Ctrl+C，or 'kill ' command 
But apachebeat ，I must use 'kill -9' command
so I think maybe it is a bug! please check

**Comment by radoondas** [comment]
Hi,
thanks for feedback. I understand.
It looks like I cannot rule out a bug possibility.
Let's try to investigate further together to find out what happened.

Let me ask a few questions first.
1, Prior to 'kill -9' is apachebeat behaving correctly? I mean does it produce correct output and you can see your apache status also in Kibana?
2, What version of Go do you use?
3, Do you have latest version of apachebeat?
4, Did you try to turn on debug option?
5, What is your OS version and is it up to date with patches?

Let start with this few questions.

Thanks,
Rado

**Comment by kkpbbb** [comment]
1、yes, apachebeat behaving correctly before I try to stop in neight in Ctrl-C nor kill 
2、my go version is  'go1.5.1 linux/amd64' 
3、yes I use the latest version of apachebeat '1.0.0-beta2'
4、I am not sure I have turn on debug option ,in /etc/apachebeat/apachebeat.yml
logging: 
  to_syslog: true
  level: debug
And when I stop apachebeat use kill ,I saw the log

" Background saving terminated with success"

But acturly it  not stop

BTW ,I use go-daemon from https://github.com/tsg/go-daemon.git to star the apachebeat

the init script file is simulate to the topbeat 
5、My OS version is 
2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 
CentOS release 6.6 (Final)
I am not sure I have apply all the patches.
BTW I compile another community beats they do exit well!

sorry for by bad english !

Thanks.

**Comment by radoondas** [comment]
Thanks,
Let's try more. Can we try to simplify the use case?

1, Install the latest GO (1.5.3)
2, checkout the latest version of apachebeat. Not beta2 release.
3, please run apachebeat without go-daemon
4, keep it running and then try to stop it by simple kill, or Crtl+C

Try to run it from command line:
./apachebeat -c /path/to/etc/apachebeat.yml

Meanwhile, I'll try to use and check on do-daemon. Maybe, I can replicate it localy and find out more.
Thanks

**Comment by kkpbbb** [comment]
I install the last go ver 1.5.3 
and every thing ok，it can normal stop apachebeat

thanks

**Comment by radoondas** [comment]
Hi,
thanks for your verification. 
I appreciate all your inpu.
Rado
